"""
VEDRAQ Core — Incident Reporting & Management Test Suite
=========================================================
Tests for Part 1-8 of the Incident Reporting Backend:
- Empty list initialization
- POST /api/incidents schema validation, authoritative ID and server timestamp generation
- GET /api/incidents retrieval and ordering
- GET /api/incidents/{id} specific lookup and 404 handling
- PATCH /api/incidents/{id} valid status transitions and invalid status rejection
- Coordinate boundary validation
- Multiple incidents with guaranteed unique IDs
- Derived nearest zone metadata
- Persistence across sequential calls during process lifetime
"""

import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.services.incident_service import incident_store

client = TestClient(app)


@pytest.fixture(autouse=True)
def clean_incident_store():
    """Reset the incident store before each test to ensure test isolation."""
    incident_store.clear()
    yield
    incident_store.clear()


def test_empty_incident_list_initially():
    """10. Empty incident list initially."""
    response = client.get("/api/incidents")
    assert response.status_code == 200
    data = response.json()
    assert data["total"] == 0
    assert data["incidents"] == []


def test_create_valid_incident():
    """1. POST /api/incidents with valid payload."""
    payload = {
        "title": "Severe Flash Flood near Dashashwamedh Ghat",
        "description": "Ganga backflow flooding main pedestrian approach. Water level 1.2m above normal.",
        "disaster_type": "FLOOD",
        "severity": "CRITICAL",
        "latitude": 25.3060,
        "longitude": 83.0100,
        "address": "Dashashwamedh Ghat Road, Varanasi",
        "reporter_id": "RESP-001",
        "people_affected_estimate": 450,
        "client_incident_id": "client-uuid-12345",
        "source": "VEDRAQ_APP",
    }
    response = client.post("/api/incidents", json=payload)
    assert response.status_code == 201
    data = response.json()

    # Authoritative fields generated by server
    assert data["id"].startswith("INC-")
    assert len(data["id"]) >= 12
    assert "created_at" in data
    assert "updated_at" in data
    assert data["status"] == "REPORTED"

    # Client fields preserved
    assert data["title"] == payload["title"]
    assert data["description"] == payload["description"]
    assert data["disaster_type"] == "FLOOD"
    assert data["severity"] == "CRITICAL"
    assert data["latitude"] == 25.3060
    assert data["longitude"] == 83.0100
    assert data["address"] == payload["address"]
    assert data["reporter_id"] == "RESP-001"
    assert data["people_affected_estimate"] == 450
    assert data["client_incident_id"] == "client-uuid-12345"

    # Initial history entry
    assert len(data["history"]) == 1
    assert data["history"][0]["status"] == "REPORTED"


def test_server_generates_authoritative_id_and_timestamp():
    """Server generates authoritative incident ID and timestamp; client cannot override ID."""
    payload = {
        "title": "Urban Waterlogging",
        "description": "Street drain overflow",
        "disaster_type": "FLOOD",
        "severity": "MODERATE",
        "latitude": 25.3100,
        "longitude": 83.0000,
        "id": "CLIENT-INVENTED-FAKE-ID",  # Should NOT be used as the authoritative ID
    }
    response = client.post("/api/incidents", json=payload)
    assert response.status_code == 201
    data = response.json()
    assert data["id"] != "CLIENT-INVENTED-FAKE-ID"
    assert data["id"].startswith("INC-")


def test_get_all_incidents():
    """2. GET /api/incidents returns list of stored reports."""
    # Create two incidents
    p1 = {
        "title": "Submerged Crossing",
        "description": "Culvert blocked",
        "disaster_type": "FLOOD",
        "severity": "HIGH",
        "latitude": 25.3150,
        "longitude": 83.0050,
    }
    p2 = {
        "title": "Power Line Down",
        "description": "Feeder transformer short-circuit",
        "disaster_type": "INFRASTRUCTURE_FAILURE",
        "severity": "CRITICAL",
        "latitude": 25.3200,
        "longitude": 83.0150,
    }
    r1 = client.post("/api/incidents", json=p1)
    r2 = client.post("/api/incidents", json=p2)
    assert r1.status_code == 201
    assert r2.status_code == 201

    get_resp = client.get("/api/incidents")
    assert get_resp.status_code == 200
    data = get_resp.json()
    assert data["total"] == 2
    assert len(data["incidents"]) == 2
    # Verify both incident IDs are in the response
    ids = [i["id"] for i in data["incidents"]]
    assert r1.json()["id"] in ids
    assert r2.json()["id"] in ids


def test_get_incident_by_id():
    """3. GET /api/incidents/{id} retrieves specific report."""
    create_resp = client.post(
        "/api/incidents",
        json={
            "title": "Chemical Spill at Depot",
            "description": "Chlorine canister leakage in storage bay 2",
            "disaster_type": "HAZMAT",
            "severity": "CRITICAL",
            "latitude": 25.3150,
            "longitude": 83.0650,
        },
    )
    inc_id = create_resp.json()["id"]

    get_resp = client.get(f"/api/incidents/{inc_id}")
    assert get_resp.status_code == 200
    fetched = get_resp.json()
    assert fetched["id"] == inc_id
    assert fetched["title"] == "Chemical Spill at Depot"
    assert fetched["disaster_type"] == "HAZMAT"


def test_get_incident_by_id_not_found():
    """GET /api/incidents/{id} returns 404 for unknown ID."""
    response = client.get("/api/incidents/INC-DOES-NOT-EXIST")
    assert response.status_code == 404
    assert "not found" in response.json()["detail"].lower()


def test_patch_incident_status_valid():
    """4. PATCH /api/incidents/{id} controlled lifecycle transitions."""
    create_resp = client.post(
        "/api/incidents",
        json={
            "title": "Landslide on Mountain Pass",
            "description": "Debris blocking both lanes",
            "disaster_type": "LANDSLIDE",
            "severity": "HIGH",
            "latitude": 27.750,
            "longitude": 85.550,
        },
    )
    inc_id = create_resp.json()["id"]

    # Transition 1: ACKNOWLEDGED
    r1 = client.patch(
        f"/api/incidents/{inc_id}",
        json={"status": "ACKNOWLEDGED", "note": "Dispatch coordinator assigned"},
    )
    assert r1.status_code == 200
    assert r1.json()["status"] == "ACKNOWLEDGED"
    assert len(r1.json()["history"]) == 2

    # Transition 2: IN_PROGRESS
    r2 = client.patch(
        f"/api/incidents/{inc_id}",
        json={"status": "IN_PROGRESS", "note": "Bulldozer and rescue team en route"},
    )
    assert r2.status_code == 200
    assert r2.json()["status"] == "IN_PROGRESS"
    assert len(r2.json()["history"]) == 3

    # Transition 3: RESOLVED
    r3 = client.patch(
        f"/api/incidents/{inc_id}",
        json={"status": "RESOLVED", "note": "Road cleared and verified safe"},
    )
    assert r3.status_code == 200
    assert r3.json()["status"] == "RESOLVED"
    assert len(r3.json()["history"]) == 4


def test_patch_incident_invalid_status():
    """6. Invalid status is strictly rejected."""
    create_resp = client.post(
        "/api/incidents",
        json={
            "title": "Bridge Structural Issue",
            "description": "Crack observed",
            "disaster_type": "INFRASTRUCTURE_FAILURE",
            "severity": "HIGH",
            "latitude": 25.310,
            "longitude": 83.010,
        },
    )
    inc_id = create_resp.json()["id"]

    # Test completely invalid status
    invalid_resp = client.patch(
        f"/api/incidents/{inc_id}",
        json={"status": "ARBITRARY_INVALID_STATUS"},
    )
    assert invalid_resp.status_code == 422


def test_invalid_incident_payload_missing_title():
    """5. Invalid payload: missing or empty title returns 422."""
    payload = {
        "title": "",  # Empty title violates min_length=1
        "description": "Water overflowing",
        "disaster_type": "FLOOD",
        "severity": "HIGH",
        "latitude": 25.310,
        "longitude": 83.010,
    }
    response = client.post("/api/incidents", json=payload)
    assert response.status_code == 422


def test_invalid_incident_payload_coordinates():
    """9. Latitude/longitude boundary validation (-90 to 90, -180 to 180)."""
    # Latitude out of bounds (> 90)
    bad_lat = {
        "title": "Invalid Lat Test",
        "description": "Testing lat validation",
        "disaster_type": "OTHER",
        "severity": "LOW",
        "latitude": 95.5,
        "longitude": 83.0,
    }
    r1 = client.post("/api/incidents", json=bad_lat)
    assert r1.status_code == 422

    # Longitude out of bounds (< -180)
    bad_lon = {
        "title": "Invalid Lon Test",
        "description": "Testing lon validation",
        "disaster_type": "OTHER",
        "severity": "LOW",
        "latitude": 25.0,
        "longitude": -195.0,
    }
    r2 = client.post("/api/incidents", json=bad_lon)
    assert r2.status_code == 422


def test_multiple_incidents_unique_ids():
    """7 & 8. Multiple incidents generate guaranteed unique IDs."""
    ids = set()
    for i in range(10):
        resp = client.post(
            "/api/incidents",
            json={
                "title": f"Incident {i}",
                "description": f"Description for incident {i}",
                "disaster_type": "FLOOD",
                "severity": "MODERATE",
                "latitude": 25.310 + (i * 0.001),
                "longitude": 83.010 + (i * 0.001),
            },
        )
        assert resp.status_code == 201
        inc_id = resp.json()["id"]
        assert inc_id not in ids
        ids.add(inc_id)

    assert len(ids) == 10

    # Verify all 10 are retrieved
    list_resp = client.get("/api/incidents")
    assert list_resp.status_code == 200
    assert list_resp.json()["total"] == 10


def test_nearest_zone_metadata_derived():
    """Zone association: derives nearest zone metadata without altering coordinates."""
    # Near Varanasi Dashashwamedh Ghat (Z01 is around 25.305, 83.010)
    resp = client.post(
        "/api/incidents",
        json={
            "title": "Ghat Embankment Leakage",
            "description": "Water seepage near river sector",
            "disaster_type": "FLOOD",
            "severity": "HIGH",
            "latitude": 25.305,
            "longitude": 83.010,
        },
    )
    assert resp.status_code == 201
    data = resp.json()
    # Check that original coordinates are preserved exactly
    assert data["latitude"] == 25.305
    assert data["longitude"] == 83.010
    # Check that nearest zone is derived
    assert data["nearest_zone_id"] is not None
    assert data["nearest_zone_name"] is not None
    assert data["nearest_zone_distance_km"] is not None
    assert data["nearest_zone_distance_km"] >= 0.0


def test_incident_persistence_during_process_lifetime():
    """11. Incident persistence across sequential calls."""
    # Create incident
    resp = client.post(
        "/api/incidents",
        json={
            "title": "Persistent Incident",
            "description": "Must persist across sequential requests",
            "disaster_type": "CYCLONE",
            "severity": "CRITICAL",
            "latitude": 25.315,
            "longitude": 83.065,
        },
    )
    inc_id = resp.json()["id"]

    # Multiple reads
    for _ in range(3):
        r = client.get(f"/api/incidents/{inc_id}")
        assert r.status_code == 200
        assert r.json()["id"] == inc_id

    # Update status
    client.patch(f"/api/incidents/{inc_id}", json={"status": "ACKNOWLEDGED"})

    # Verify update persisted
    r_after = client.get(f"/api/incidents/{inc_id}")
    assert r_after.status_code == 200
    assert r_after.json()["status"] == "ACKNOWLEDGED"


def test_locations_catalog_endpoint():
    """Verify GET /api/locations exposes scenario centers and tactical zones."""
    resp = client.get("/api/locations")
    assert resp.status_code == 200
    data = resp.json()
    assert "locations" in data
    assert data["total"] >= 25
    ids = {loc["id"] for loc in data["locations"]}
    assert "varanasi_center" in ids
    assert "nepal_center" in ids
    assert "Z01" in ids
    assert "N07" in ids


def test_location_consistency_varanasi_selected_city_not_equal_nearest_zone():
    """
    Selected city != nearest tactical zone case:
    Operator reports incident from Varanasi Center (25.3150, 83.0650).
    Address is preserved as 'Varanasi Center', and Core assigns nearest tactical zone 'Z14 Chaukaghat' (0.87 km).
    """
    payload = {
        "title": "Central Command Perimeter Flood",
        "description": "Rising floodwaters at central Varanasi sector",
        "disaster_type": "FLOOD",
        "severity": "HIGH",
        "latitude": 25.3150,
        "longitude": 83.0650,
        "address": "Varanasi Center",
    }
    resp = client.post("/api/incidents", json=payload)
    assert resp.status_code == 201
    data = resp.json()

    # Original coordinates and address are strictly preserved
    assert data["latitude"] == 25.3150
    assert data["longitude"] == 83.0650
    assert data["address"] == "Varanasi Center"

    # Nearest tactical zone is Chaukaghat (Z14)
    assert data["nearest_zone_id"] == "Z14"
    assert data["nearest_zone_name"] == "Chaukaghat"
    assert data["nearest_zone_distance_km"] < 1.5

    # Verification: selected city/address != nearest tactical zone name
    assert data["address"] != data["nearest_zone_name"]


def test_location_consistency_dhulikhel_nepal():
    """
    Cross-scenario consistency:
    Incident reported in Dhulikhel, Nepal (27.6180, 85.5540).
    Must resolve to Nepal zone N07 (Dhulikhel Gateway), NEVER to a Varanasi zone.
    """
    payload = {
        "title": "Mountain Highway Landslide",
        "description": "Massive rockfall blocking entry to Dhulikhel",
        "disaster_type": "LANDSLIDE",
        "severity": "CRITICAL",
        "latitude": 27.6180,
        "longitude": 85.5540,
        "address": "Dhulikhel Gateway, Bagmati",
    }
    resp = client.post("/api/incidents", json=payload)
    assert resp.status_code == 201
    data = resp.json()

    assert data["latitude"] == 27.6180
    assert data["longitude"] == 85.5540
    assert data["address"] == "Dhulikhel Gateway, Bagmati"

    # Correct Nepal zone
    assert data["nearest_zone_id"] == "N07"
    assert data["nearest_zone_name"] == "Dhulikhel Gateway"
    assert data["nearest_zone_distance_km"] <= 0.05


def test_location_consistency_banepa_nepal():
    """
    Cross-scenario consistency:
    Incident reported in Banepa, Nepal (27.6320, 85.5240).
    Must resolve to Nepal zone N08 (Banepa Lowlands), NEVER to a Varanasi zone.
    """
    payload = {
        "title": "Flash Flood in Lowland Market",
        "description": "River swelling and submerging commercial area",
        "disaster_type": "FLOOD",
        "severity": "HIGH",
        "latitude": 27.6320,
        "longitude": 85.5240,
        "address": "Banepa Lowlands Market",
    }
    resp = client.post("/api/incidents", json=payload)
    assert resp.status_code == 201
    data = resp.json()

    assert data["latitude"] == 27.6320
    assert data["longitude"] == 85.5240
    assert data["address"] == "Banepa Lowlands Market"

    # Correct Nepal zone
    assert data["nearest_zone_id"] == "N08"
    assert data["nearest_zone_name"] == "Banepa Lowlands"
    assert data["nearest_zone_distance_km"] <= 0.05

